### PR TITLE
Use lcovonly reporter.

### PR DESCRIPTION
**Pull request by davidlehn**

### CODE REVIEW

**Comment by davidlehn** [comment]
The coverage uploads apparently can fail with 403, but the action will pass.  That's going to lead to confusion.

**Comment by OR13** [comment]
PR has been open for 11 days, no review.

**Comment by mattcollier** [comment]
@davidlehn do we still need the `coverage-report` script?

I've been getting by with just doing: 'firefox coverage/lcov-report/index.html'

**Comment by davidlehn** [comment]
[There's probably a better place for this discussion] After my previous coverage setup polluted many of our repos, I have a better idea of what I'd like.  I think we should have at least a "coverage" target that uses "lcov" (which is lcov+html output) and "text-summary" reporters.  That gets you pretty html and a quick summary.  Then have a "coverage-ci" target that does the "lcovonly" output for the robots to look at.  As far as the "coverage-report" target, I personally use that to just get the default "text" reporter output table and details.  I imagine this is a personal preference, so I'm not sure what to do.  If no one else wants that, then I can "./node_modules/.bin/nyc report" by hand if need be.  Kind of annoying, which is why I added the script in the first place.  Related is that we should remove the default reporters from package.json config (I'll do that here in a minute).

**Comment by davidlehn** [comment]
Merging.  Can update script usage later if needed.

**Pull request merged**
